name-template: 'v$RESOLVED_VERSION 🚩'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Maintenance'
    label:
      - 'refactor'
      - 'ci'
      - 'docs'

  - title: '‼️ Breaking Changes'
    label:
      - breaking-changes
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - breaking-changes
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - feature
      - bugfix
      - ci
      - docs
      - refactor
      - 'patch'
  default: patch
template: |
  Here are the changes made for v$RESOLVED_VERSION:

  $CHANGES
autolabeler:
  - label: breaking-changes
    title:
      - /breaking(-| )?changes/i
      - /^(feat|fix|refactor|docs|ci)(\([^)]+\))?!+.+/i
      - /^!!/i

  - label: bugfix
    title: '/fix/i'
    branch:
      - '/fix\/.+/'

  - label: feature
    title: '/feat(ure)?/i'
    branch:
      - '/feat\/.+/'

  - label: refactor
    title: '/refactor/i'
    branch:
      - '/refactor\/.+/'

  - label: docs
    title: '/doc(s|umentation)/i'
    files:
      - '*.md'
      - '.gitignore'
    branch:
      - '/docs\/.+/'

  - label: ci
    files:
      - '.github/**/*.yml'
    branch:
      - '/ci\/.+/'