name-template: 'v$RESOLVED_VERSION 🚩'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Maintenance'
    label:
      - 'refactor'
      - 'ci'
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  Here are the changes made for v$RESOLVED_VERSION:

  $CHANGES
autolabeler:
  - label: bugfix
    title: '/fix/i'
    body: '/fix/i'

  - label: feature
    title: '/feat(ure)?/i'
    body: '/feat(ure)?/i'

  - label: refactor
    title: '/refactor/i'
    body: '/refactor/i'

  - label: docs
    title: '/doc(s|umentation)/i'
    body: '/doc(s|umentation)/i'
    files:
      - '*.md'

  - label: ci
    title: '/ci/i'
    body: '/ci/i'
    files:
      - '.github/**/*.yml'