name: Master Branch On Push

on:
  push:
    branches:
      - master

jobs:
  release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  push-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: oxi-build
        uses: ./.github/workflows/build.yml
      
      - name: Download oxi-build artifact
        uses: actions/download-artifact@v3
        with:
          name: oxi-build
      
      - name: git status
        run: git status